name: Test

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false # Keep the '2.x' test from stopping the other jobs
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [ '2.x', '3.8', '3.9', '3.10' ]
    runs-on: ${{ matrix.os }}
    name: Testing with Python ${{ matrix.python-version }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: pip install --upgrade pip
      - run: pip install --requirement requirements.txt
      - run: python lookup.py LAX
